config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get 'tasks', to: "tasks#index"
  get "tasks/new", to: "tasks#new", as: :task_new
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/edit/:id", to: "tasks#edit", as: :task_edit
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: :task_delete

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :task_find, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(strong_param)
    if @task.save!
      redirect_to @task
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(strong_param)
      redirect_to @task
    else
      render :index
    end
  end

  def destroy
    if @task.destroy
      redirect_to tasks_path
    end
  end

  private

  def task_find
    @task = Task.find(params[:id])
  end

  def strong_param
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit</h1>

<%= form_with model: @task do |form| %>
  <%= form.text_field :title %>
  <%= form.text_area :details %>
  <%= check_box_tag(:completed)%>
  <%= form.submit %>
<% end %>

<%=link_to "menu", tasks_path%>

app/views/tasks/index.html.erb
<h1>Index</h1>
<%@tasks.each do |task|%>
  <p><%= link_to "#{task.title}", task_path(task.id)%></p>
  <input type="checkbox" <%="checked" if task.completed == true %>/>
<%end%>

  <%= link_to 'Add new task', task_new_path, class: 'btn btn-primary' %>

app/views/tasks/new.html.erb
<h1>New</h1>

<%= form_with model: @task do |form| %>
  <%= form.text_field :title %>
  <%= form.text_area :details %>
  <%= check_box_tag(:completed) %>
  <%= form.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Show</h1>

<p><%= @task.title%></p>
<p><%= @task.details%></p>
<p><%= @task.completed%></p>
  <%= link_to 'Edit', task_edit_path(@task.id), class: 'btn btn-primary' %>
  <%= link_to "remove", task_delete_path(@task.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>